# Generated by Django 2.1.4 on 2018-12-11 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Foto')),
                ('pdf', models.FileField(upload_to='pdfs/%Y/%m/%d/', verbose_name='PDF ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de adhesión')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
    ]
