# Generated by Django 2.1.4 on 2018-12-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20181211_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.Curso', verbose_name='Curso'),
        ),
    ]
